### ISSUE TITLE
Add fixtures framework + commands

### ISSUE THREAD

**Issue by ryanolee** [Multiplied-By-One/MBOne-Backend#1]
## Problem:
When starting out with local dev using this app we have no data available to use. This can be problematic given it means we each need to manually create data for our DB every time we want to try some local dev

## Aims:
Use a package like https://github.com/RobinCK/typeorm-fixtures to to create a fixture where a single user is created.

**Comment by tsukimi2** [comment]
@ryanolee I'll have a try at this issue. ^_^

**Comment by ryanolee** [comment]
Sure thanks for picking this up @tsukimi2 ! Let me know if you need any help getting things set up!

**Comment by tsukimi2** [comment]
Closing issue with merged code above.
